project:
  type: website

website:
  title: "The Neural Notebook"
  description: "A blog about coding (python, DL) and some other stuff"
  navbar:
    background: dark
    logo: space.jpeg
    right:
      - text: About
        href: about.qmd
      - text: Archive
        # href: archive.qmd
      - text: Series
        # href: link_to_series
    
    tools:
      - icon: github
        href: https://github.com/Iamalos
        aria-label: Github
      - icon: twitter
        href: https://x.com/DolgushevI64783
        aria-label: Twitter
    search: True
    collapse: True
    
format:
  html:
    theme: darkly
    css: styles.css



